//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityInventoryItemType
    {
        public FacilityInventoryItemType()
        {
            this.FacilitySaleItems = new HashSet<FacilitySaleItem>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> InventoryItemTypeId { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuantityOnHand { get; set; }
        public Nullable<int> QuantityOnOrder { get; set; }
        public string SKU { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public decimal Price { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual InventoryItemType InventoryItemType { get; set; }
        public virtual ICollection<FacilitySaleItem> FacilitySaleItems { get; set; }
    }
}
