//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilitySale
    {
        public FacilitySale()
        {
            this.FacilitySaleItems = new HashSet<FacilitySaleItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int FacilityId { get; set; }
        public bool Completed { get; set; }
        public string CustomerName { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual ICollection<FacilitySaleItem> FacilitySaleItems { get; set; }
    }
}
