//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.Facilities1 = new HashSet<Facility>();
            this.FacilityInventoryItemTypes = new HashSet<FacilityInventoryItemType>();
            this.FacilitySales = new HashSet<FacilitySale>();
            this.FacilityUsers = new HashSet<FacilityUser>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentFacilityId { get; set; }
        public int TenantId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Facility> Facilities1 { get; set; }
        public virtual Facility Facility1 { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<FacilityInventoryItemType> FacilityInventoryItemTypes { get; set; }
        public virtual ICollection<FacilitySale> FacilitySales { get; set; }
        public virtual ICollection<FacilityUser> FacilityUsers { get; set; }
    }
}
