//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevDetectiveEntities1 : DbContext
    {
        public DevDetectiveEntities1()
            : base("name=DevDetectiveEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<FacilityInventoryItemType> FacilityInventoryItemTypes { get; set; }
        public DbSet<FacilitySaleItem> FacilitySaleItems { get; set; }
        public DbSet<FacilitySale> FacilitySales { get; set; }
        public DbSet<FacilityUser> FacilityUsers { get; set; }
        public DbSet<InventoryItemType> InventoryItemTypes { get; set; }
        public DbSet<Tenant> Tenants { get; set; }
    }
}
